// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: eng

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, 522);
    lv_obj_set_height(ui_Label2, 42);
    lv_obj_set_x(ui_Label2, -634);
    lv_obj_set_y(ui_Label2, -310);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "BLTN_CAM Engineer Mode");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_HomeBtn, 186);
    lv_obj_set_height(ui_HomeBtn, 55);
    lv_obj_set_x(ui_HomeBtn, -282);
    lv_obj_set_y(ui_HomeBtn, -315);
    lv_obj_set_align(ui_HomeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HomeBtn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -8);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "HOME");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 948);
    lv_obj_set_height(ui_TextArea2, 528);
    lv_obj_set_x(ui_TextArea2, -635);
    lv_obj_set_y(ui_TextArea2, -5);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextArea2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TextArea2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 874);
    lv_obj_set_height(ui_Panel2, 507);
    lv_obj_set_x(ui_Panel2, 701);
    lv_obj_set_y(ui_Panel2, -11);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_UpdateBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_UpdateBtn, 360);
    lv_obj_set_height(ui_UpdateBtn, 90);
    lv_obj_set_x(ui_UpdateBtn, -220);
    lv_obj_set_y(ui_UpdateBtn, -200);
    lv_obj_set_align(ui_UpdateBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UpdateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UpdateBtn, lv_color_hex(0x0B0C11), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UpdateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_UpdateBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_UpdateBtn, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_UpdateBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_UpdateBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_UpdateBtn, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_UpdateBtn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "UPDATE");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClearDtcBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_ClearDtcBtn, 360);
    lv_obj_set_height(ui_ClearDtcBtn, 90);
    lv_obj_set_x(ui_ClearDtcBtn, 230);
    lv_obj_set_y(ui_ClearDtcBtn, -200);
    lv_obj_set_align(ui_ClearDtcBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClearDtcBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ClearDtcBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ClearDtcBtn, lv_color_hex(0x0C1722), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClearDtcBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClearDtcBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ClearDtcBtn, lv_color_hex(0x838F06), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ClearDtcBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ClearDtcBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ClearDtcBtn, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label4 = lv_label_create(ui_ClearDtcBtn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "CLEAR DTC");
    lv_label_set_recolor(ui_Label4, "true");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RebootBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_RebootBtn, 360);
    lv_obj_set_height(ui_RebootBtn, 90);
    lv_obj_set_x(ui_RebootBtn, -220);
    lv_obj_set_y(ui_RebootBtn, -100);
    lv_obj_set_align(ui_RebootBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RebootBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RebootBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RebootBtn, lv_color_hex(0x0A0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RebootBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RebootBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RebootBtn, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_RebootBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_RebootBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_RebootBtn, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_RebootBtn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "REBOOT");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DltDownloadBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_DltDownloadBtn, 360);
    lv_obj_set_height(ui_DltDownloadBtn, 90);
    lv_obj_set_x(ui_DltDownloadBtn, 230);
    lv_obj_set_y(ui_DltDownloadBtn, -100);
    lv_obj_set_align(ui_DltDownloadBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DltDownloadBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DltDownloadBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DltDownloadBtn, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DltDownloadBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DltDownloadBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DltDownloadBtn, lv_color_hex(0x056F6C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_DltDownloadBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_DltDownloadBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_DltDownloadBtn, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_DltDownloadBtn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "DLT DOWNLOAD");
    lv_label_set_recolor(ui_Label6, "true");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnParkModeBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_EnParkModeBtn, 360);
    lv_obj_set_height(ui_EnParkModeBtn, 90);
    lv_obj_set_x(ui_EnParkModeBtn, -220);
    lv_obj_set_y(ui_EnParkModeBtn, -3);
    lv_obj_set_align(ui_EnParkModeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EnParkModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EnParkModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EnParkModeBtn, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnParkModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnParkModeBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_EnParkModeBtn, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_EnParkModeBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_EnParkModeBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_EnParkModeBtn, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label7 = lv_label_create(ui_EnParkModeBtn);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 9);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "ENABLE PARK MODE\n      WO/Aux Bat.");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label7, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Label7, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Label7, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_DeParkModeBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_DeParkModeBtn, 360);
    lv_obj_set_height(ui_DeParkModeBtn, 90);
    lv_obj_set_x(ui_DeParkModeBtn, 230);
    lv_obj_set_y(ui_DeParkModeBtn, -2);
    lv_obj_set_align(ui_DeParkModeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeParkModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DeParkModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DeParkModeBtn, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeParkModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeParkModeBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DeParkModeBtn, lv_color_hex(0x0E75A8), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_DeParkModeBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_DeParkModeBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_DeParkModeBtn, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label8 = lv_label_create(ui_DeParkModeBtn);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, 3);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "DISABLE PARK MODE\n      WO/Aux Bat.");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GsensorLogOnBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_GsensorLogOnBtn, 360);
    lv_obj_set_height(ui_GsensorLogOnBtn, 90);
    lv_obj_set_x(ui_GsensorLogOnBtn, -220);
    lv_obj_set_y(ui_GsensorLogOnBtn, 100);
    lv_obj_set_align(ui_GsensorLogOnBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GsensorLogOnBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GsensorLogOnBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GsensorLogOnBtn, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GsensorLogOnBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GsensorLogOnBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GsensorLogOnBtn, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_GsensorLogOnBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_GsensorLogOnBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_GsensorLogOnBtn, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label9 = lv_label_create(ui_GsensorLogOnBtn);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "G-SENSOR\n  LOG ON");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GsensorLogOffBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_GsensorLogOffBtn, 360);
    lv_obj_set_height(ui_GsensorLogOffBtn, 90);
    lv_obj_set_x(ui_GsensorLogOffBtn, 230);
    lv_obj_set_y(ui_GsensorLogOffBtn, 100);
    lv_obj_set_align(ui_GsensorLogOffBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GsensorLogOffBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GsensorLogOffBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GsensorLogOffBtn, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GsensorLogOffBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GsensorLogOffBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GsensorLogOffBtn, lv_color_hex(0xE38910), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_GsensorLogOffBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_GsensorLogOffBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_GsensorLogOffBtn, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label10 = lv_label_create(ui_GsensorLogOffBtn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -1);
    lv_obj_set_y(ui_Label10, 1);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "G-SENSOR\n  LOG OFF");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GsensorLogDwlnBtn = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_GsensorLogDwlnBtn, 360);
    lv_obj_set_height(ui_GsensorLogDwlnBtn, 90);
    lv_obj_set_x(ui_GsensorLogDwlnBtn, -220);
    lv_obj_set_y(ui_GsensorLogDwlnBtn, 200);
    lv_obj_set_align(ui_GsensorLogDwlnBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GsensorLogDwlnBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GsensorLogDwlnBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GsensorLogDwlnBtn, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GsensorLogDwlnBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GsensorLogDwlnBtn, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GsensorLogDwlnBtn, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_GsensorLogDwlnBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_GsensorLogDwlnBtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_GsensorLogDwlnBtn, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label11 = lv_label_create(ui_GsensorLogDwlnBtn);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -5);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "     G-SENSOR\nLOG DOWNLOAD");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_hdharmony32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeBtn, ui_event_HomeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UpdateBtn, ui_event_UpdateBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClearDtcBtn, ui_event_ClearDtcBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RebootBtn, ui_event_RebootBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DltDownloadBtn, ui_event_DltDownloadBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EnParkModeBtn, ui_event_EnParkModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DeParkModeBtn, ui_event_DeParkModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GsensorLogOnBtn, ui_event_GsensorLogOnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GsensorLogOffBtn, ui_event_GsensorLogOffBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GsensorLogDwlnBtn, ui_event_GsensorLogDwlnBtn, LV_EVENT_ALL, NULL);

}
