// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: eng

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Label2;
void ui_event_HomeBtn(lv_event_t * e);
lv_obj_t * ui_HomeBtn;
lv_obj_t * ui_Label1;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Panel2;
void ui_event_UpdateBtn(lv_event_t * e);
lv_obj_t * ui_UpdateBtn;
lv_obj_t * ui_Label3;
void ui_event_ClearDtcBtn(lv_event_t * e);
lv_obj_t * ui_ClearDtcBtn;
lv_obj_t * ui_Label4;
void ui_event_RebootBtn(lv_event_t * e);
lv_obj_t * ui_RebootBtn;
lv_obj_t * ui_Label5;
void ui_event_DltDownloadBtn(lv_event_t * e);
lv_obj_t * ui_DltDownloadBtn;
lv_obj_t * ui_Label6;
void ui_event_EnParkModeBtn(lv_event_t * e);
lv_obj_t * ui_EnParkModeBtn;
lv_obj_t * ui_Label7;
void ui_event_DeParkModeBtn(lv_event_t * e);
lv_obj_t * ui_DeParkModeBtn;
lv_obj_t * ui_Label8;
void ui_event_GsensorLogOnBtn(lv_event_t * e);
lv_obj_t * ui_GsensorLogOnBtn;
lv_obj_t * ui_Label9;
void ui_event_GsensorLogOffBtn(lv_event_t * e);
lv_obj_t * ui_GsensorLogOffBtn;
lv_obj_t * ui_Label10;
void ui_event_GsensorLogDwlnBtn(lv_event_t * e);
lv_obj_t * ui_GsensorLogDwlnBtn;
lv_obj_t * ui_Label11;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HomeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HomeBtnClicked(e);
    }
}
void ui_event_UpdateBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        UpdateBtnClicked(e);
    }
}
void ui_event_ClearDtcBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ClearDtcBtnClicked(e);
    }
}
void ui_event_RebootBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        RebootBtnClicked(e);
    }
}
void ui_event_DltDownloadBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DltDownloadBtnClicked(e);
    }
}
void ui_event_EnParkModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        EnParkModeBtnClicked(e);
    }
}
void ui_event_DeParkModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DisableParkModeBtnClicked(e);
    }
}
void ui_event_GsensorLogOnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GsensorLogOnBtnClicked(e);
    }
}
void ui_event_GsensorLogOffBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GsensorLogOffBtnClicked(e);
    }
}
void ui_event_GsensorLogDwlnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GsensorLogOnBtnClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
