// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: eng

#ifndef _ENG_UI_H
#define _ENG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
void ui_event_HomeBtn(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Panel2;
void ui_event_UpdateBtn(lv_event_t * e);
extern lv_obj_t * ui_UpdateBtn;
extern lv_obj_t * ui_Label3;
void ui_event_ClearDtcBtn(lv_event_t * e);
extern lv_obj_t * ui_ClearDtcBtn;
extern lv_obj_t * ui_Label4;
void ui_event_RebootBtn(lv_event_t * e);
extern lv_obj_t * ui_RebootBtn;
extern lv_obj_t * ui_Label5;
void ui_event_DltDownloadBtn(lv_event_t * e);
extern lv_obj_t * ui_DltDownloadBtn;
extern lv_obj_t * ui_Label6;
void ui_event_EnParkModeBtn(lv_event_t * e);
extern lv_obj_t * ui_EnParkModeBtn;
extern lv_obj_t * ui_Label7;
void ui_event_DeParkModeBtn(lv_event_t * e);
extern lv_obj_t * ui_DeParkModeBtn;
extern lv_obj_t * ui_Label8;
void ui_event_GsensorLogOnBtn(lv_event_t * e);
extern lv_obj_t * ui_GsensorLogOnBtn;
extern lv_obj_t * ui_Label9;
void ui_event_GsensorLogOffBtn(lv_event_t * e);
extern lv_obj_t * ui_GsensorLogOffBtn;
extern lv_obj_t * ui_Label10;
void ui_event_GsensorLogDwlnBtn(lv_event_t * e);
extern lv_obj_t * ui_GsensorLogDwlnBtn;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_hdharmony24);
LV_FONT_DECLARE(ui_font_hdharmony28);
LV_FONT_DECLARE(ui_font_hdharmony32);
LV_FONT_DECLARE(ui_font_hdharmony32B);
LV_FONT_DECLARE(ui_font_hdharmony28B);
LV_FONT_DECLARE(ui_font_hdharmony24B);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
