// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: eng

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void HomeBtnClicked(lv_event_t * e);
void UpdateBtnClicked(lv_event_t * e);
void ClearDtcBtnClicked(lv_event_t * e);
void RebootBtnClicked(lv_event_t * e);
void DltDownloadBtnClicked(lv_event_t * e);
void EnParkModeBtnClicked(lv_event_t * e);
void DisableParkModeBtnClicked(lv_event_t * e);
void GsensorLogOnBtnClicked(lv_event_t * e);
void GsensorLogOffBtnClicked(lv_event_t * e);
void GsensorLogOnBtnClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
