// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: eng

#include "ui.h"

void HomeBtnClicked(lv_event_t * e)
{
	// Your code here
}

void UpdateBtnClicked(lv_event_t * e)
{
	// Your code here
}

void ClearDtcBtnClicked(lv_event_t * e)
{
	// Your code here
}

void RebootBtnClicked(lv_event_t * e)
{
	// Your code here
}

void DltDownloadBtnClicked(lv_event_t * e)
{
	// Your code here
}

void EnParkModeBtnClicked(lv_event_t * e)
{
	// Your code here
}

void DisableParkModeBtnClicked(lv_event_t * e)
{
	// Your code here
}

void GsensorLogOnBtnClicked(lv_event_t * e)
{
	// Your code here
}

void GsensorLogOffBtnClicked(lv_event_t * e)
{
	// Your code here
}
